const inscricaoSucesso = "<h1 style=\"text-align: center;\"><span style=\"color: #00ccff;\"><strong>XX ENDIPE | RIO 2020</strong></span></h1> <h4 style=\"text-align: center;\"><span style=\"color: #00ccff;\"><strong>Bem-Vindo</strong></span></h4> <p>&nbsp;</p> <p><span style=\"color: #000000;\"><strong>Sua inscri&ccedil;&atilde;o foi realizada com sucesso!<br />Acompanhe a gente em nossas redes sociais para ficar por dentro de todas as novidades do congresso.</strong></span></p> <p><span style=\"color: #000000;\"><strong>Ah! E n&atilde;o se esque&ccedil;a, se for submeter trabalhos fique de olho nos prazos e pagamentos para n&atilde;o perder a oportunidade.</strong></span></p> <p>&nbsp;</p> <p><span style=\"color: #000000;\"><strong><a title=\"Facebook\" href=\"https://www.facebook.com/xxendiperio2020/\" target=\"_blank\" rel=\"noopener\">Facebook</a> | <a title=\"Instagram\" href=\"https://www.instagram.com/endipe.riodejaneiro/\" target=\"_blank\" rel=\"noopener\">Instagram</a></strong></span></p> <p>&nbsp;</p> <p>&nbsp;</p>";
const pagamentoHomologado = "<h1><strong>XX ENDIPE | RIO 2020</strong></h1><p>&nbsp;</p><p>Seu pagamento foi confirmado e sua inscri&ccedil;&atilde;o homologada! Fique atento aos prazos para submiss&atilde;o de trabalhos e nos acompanhe nas redes sociais para ficar por dentro das novidades</p><p>&nbsp;</p><p><strong><a title=\"\&quot;Facebook\&quot;\" href=\"\&quot;https://www.facebook.com/xxendiperio2020/\&quot;\" target=\"\&quot;_blank\&quot;\" rel=\"\&quot;noopener\&quot;\">Facebook</a> | <a title=\"\&quot;Instagram\&quot;\" href=\"\&quot;https://www.instagram.com/endipe.riodejaneiro/\&quot;\" target=\"\&quot;_blank\&quot;\" rel=\"\&quot;noopener\&quot;\">Instagram</a></strong></p><p>&nbsp;</p><p>&nbsp;</p>";
const trabalhoSubmetido = "<h1><strong>XX ENDIPE | RIO 2020</strong>&nbsp;</h1><p>Seu trabalho foi submetido com sucesso! Obrigada por compartilhar seus fazeres-saberes conosco!</p><p>&nbsp;</p><p><strong><a title=\"\&quot;Facebook\&quot;\" href=\"\&quot;https://www.facebook.com/xxendiperio2020/\&quot;\" target=\"\&quot;_blank\&quot;\" rel=\"\&quot;noopener\&quot;\">Facebook</a> | <a title=\"\&quot;Instagram\&quot;\" href=\"\&quot;https://www.instagram.com/endipe.riodejaneiro/\&quot;\" target=\"\&quot;_blank\&quot;\" rel=\"\&quot;noopener\&quot;\">Instagram</a></strong></p><p>&nbsp;</p><p>&nbsp;</p>";
const esqueciSenha = "<h1><strong>XX ENDIPE | RIO 2020</strong>&nbsp;</h1><p>Para recuperar sua senha siga os passos abaixo:</p><p>1 - Acesse o seguinte endereço http://www.xxendiperio2020.com.br/reset-senha</p><p>2 - Insira o seguinte código no campo \"Código do email\": #senha#</p><p>3 - Insira sua nova senha no sistema e clique em Enviar</p>";

module.exports = {
    inscricaoSucesso,
    pagamentoHomologado,
    trabalhoSubmetido,
    esqueciSenha
};